{{- if .Values.authhub.backend.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: authhub-backend-config
  namespace: {{ .Release.Namespace }}
data:
  aops-config.yml: |-
{{ tpl (.Files.Get "configs/backend/aops-config.yml") . | indent 4 }}
  authhub.yml: |-
{{ tpl (.Files.Get "configs/backend/authhub.yml") . | indent 4 }}
  copy-config.yml: |-
    copy:
      - from: /config/aops-config.yml
        to: /config-rw/aops-config.yml
        mode:
          uid: 0
          gid: 0
          mode: "0o650"
        secrets:
          - /db-secrets
          - /authhub-secrets
      - from: /config/conf.d/authhub.yml
        to: /config-rw/conf.d/authhub.yml
        mode:
          uid: 0
          gid: 0
          mode: "0o650"
        secrets:
          - /db-secrets
          - /authhub-secrets
{{- end -}}
