{{- if .Values.euler_copilot.rag.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-config
  namespace: {{ .Release.Namespace }}
data:
  .env: |-
{{ tpl (.Files.Get "configs/rag/.env") . | indent 4}}
  .env-sql: |-
{{ tpl (.Files.Get "configs/rag/.env-sql") . | indent 4}}
  copy-config.yaml: |-
    copy:
      - from: /config/.env
        to: /config-rw/.env
        mode:
          uid: 1001
          gid: 1001
          mode: "0o650"
        secrets:
          - /db-secrets
          - /system-secrets
      - from: /config/.env-sql
        to: /config-rw/.env-sql
        mode:
          uid: 1001
          gid: 1001
          mode: "0o650"
        secrets:
          - /db-secrets
          - /system-secrets
{{- end -}}