# 全局设置
globals:
  # 节点架构：默认是x86
  # [必填] 节点设置：["x86", "arm"]
  arch:
  # 镜像拉取策略；默认为IfNotPresent
  imagePullPolicy:
  # 副本数，默认为1
  replicaCount:
  # 存储类名称；默认为local-path
  storageClassName:

storage:
  # MySQL持久化存储大小，默认为10Gi
  mysql:

domain:
  # [必填] AuthHub web端URL, 默认是http://127.0.0.1:30081
  authhub:

# 部署AuthHub本地鉴权服务
authhub:
  # 配置文件工具
  secret_inject:
    # 镜像设置；默认为hub.oepkgs.net/neocopilot/secret_inject:dev-x86
    # 镜像标签：["dev-x86", "dev-arm"]
    image:

  web:
    # [必填] 是否部署AuthHub前端服务
    enabled: true
    # 镜像设置；默认为hub.oepkgs.net/neocopilot/authhub-web:0.9.3-x86
    # 镜像标签：["0.9.3-x86", "0.9.3-arm"]
    image:
    # 性能限制设置
    resourceLimits: {}
    # Service设置
    service:
      # Service类型，例如NodePort
      type: NodePort
      # 当类型为NodePort时，填写主机的端口号
      nodePort: 30081

  backend:
    # [必填] 是否部署AuthHub后端服务
    enabled: true
    # 镜像设置；默认为hub.oepkgs.net/neocopilot/authhub:0.9.3-x86
    # 镜像标签：["0.9.3-x86", "0.9.3-arm"]
    image:
    # 性能限制设置
    resourceLimits: {}
    # Service设置
    service:
      # Service类型，例如NodePort
      type:
      # 当类型为NodePort时，填写主机的端口号
      nodePort:

  mysql:
    # [必填] 是否启用MySQL
    enabled: true
    # 镜像设置；默认为hub.oepkgs.net/neocopilot/mysql:8-x86
    # 镜像标签：["8-x86", "8-arm"]
    image:
    # 性能限制设置
    resourceLimits: {}
    # Service设置
    service:
      # Service类型，例如NodePort
      type:
      # 当类型为NodePort时，填写主机的端口号
      nodePort:
