{{- $databaseSecret := (lookup "v1" "Secret" .Release.Namespace "euler-copilot-database") -}}
{{- if $databaseSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: euler-copilot-database
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  redis-password: {{ index $databaseSecret.data "redis-password" | b64dec | quote }}
  mongo-password: {{ index $databaseSecret.data "mongo-password" | b64dec | quote }}
  minio-password: {{ index $databaseSecret.data "minio-password" | b64dec | quote }}
  gauss-password: {{ index $databaseSecret.data "gauss-password" | b64dec | quote }}
{{- else -}}
apiVersion: v1
kind: Secret
metadata:
  name: euler-copilot-database
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  redis-password: {{ randAlphaNum 20 | quote }}
  mongo-password: {{ randAlphaNum 20 | quote }}
  minio-password: {{ randAlphaNum 20 | quote }}
  gauss-password: {{ include "databases.generateGaussPassword" . | quote  }}
{{- end -}}
