{{- if and .Values.databases.opengauss.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opengauss-storage
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: {{ default "local-path" .Values.globals.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "10Gi" .Values.storage.opengauss }}
{{- end -}}

